Service:
  RegionId: cn-hangzhou
  DeployType: ros
  TenantType: SingleTenant
  DeployMetadata:
    AllowedRegions:
      - cn-hangzhou
      - cn-hongkong
    ServiceInstanceNameRule:
      Prefix: mysql
    SupplierDeployMetadata:
      RoleName: ${RoleName}
      UserType: Aliyun
      SupplierTemplateConfigs:
        - Name: mysql
          AllowedRegions:
            - ${RegionId}
          Url: 'templates/template.yaml'
          PredefinedParameters:
            - Name: 低配版
              Description: 1副本，20G
              Parameters:
                Storage: 20
                Replicas: 1
              Type: Normal
              OrderList:
                - Storage
                - Replicas
            - Name: 基础版
              Description: 2副本，40G
              Parameters:
                Storage: 40
                Replicas: 2
              Type: Normal
              OrderList:
                - Storage
                - Replicas
            - Name: 高配版
              Description: 2副本，80G
              Parameters:
                Storage: 80
                Replicas: 2
              Type: Normal
              OrderList:
                - Storage
                - Replicas
          HiddenParameterKeys:
            - ClusterId
            - ConfigParam
            - Replicas
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - ClusterId
              ParameterValueMapping:
                ${RegionId}:
                  Parameters:
                    ClusterId: ${ClusterId}
    TemplateConfigs:
      - Name: mysql
        AllowedRegions:
          - ${RegionId}
  OperationMetadata:
    ParameterConfigs:
      - TemplateName: mysql
        Parameters:
          mysql.max_allowed_packet:
            Type: String
            Description: mysql服务器允许最大接收数的据包大小
            Default: '16M'
            AllowedPattern: \d+M
            ConstraintDescription: 数据包大小，只允许填写数字+M，例如16M
          mysql.max_connections:
            Type: Number
            Description: 最大连接数
            Default: 512
            MaxValue: 1024
            MinValue: 256
          mysql.max_user_connections:
            Type: Number
            Default: 48
            MaxValue: 64
            MinValue: 32
            Description: 用户最大的连接数
          mysql.thread_cache_size:
            Type: Number
            Default: '16'
            Description: 线程缓存
            AllowedValues:
              - 8
              - 16
              - 32
              - 64
        Metadata:
          ParameterGroups:
            - Parameters:
                - max_allowed_packet
                - max_connections
                - max_user_connections
                - thread_cache_size
              TemplateParameter: ConfigParam
              DefaultValue: |-
                [mysqld]
                bind-address=*
                default_storage_engine=InnoDB
                binlog_format=row
                innodb_autoinc_lock_mode=2
                datadir=/data1/mysql
                socket=/data1/mysql/mysql.sock
                max_allowed_packet  = 256M
                max_connections  = 512
                max_user_connections = 50
                thread_cache_size = 16
                symbolic-links=0
                sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
                
                [client]
                socket=/data1/mysql/mysql.sock
              Formatter: cnf
              Name: mysql
              FormatterConfig:
                SectionName: mysqld
    StatusOperationConfigs:
      - TemplateName: mysql
        DeployScene: ACK
        Parameters:
          - Replicas
        SupportOperations:
          - Start
          - Stop
          - Restart
    PrometheusIntegrationType: cn-mariadb
    PrometheusConfigMap:
      mysql:
        EnablePrometheus: true
        GrafanaDashBoardTitle: MySQL Exporter Quickstart and Dashboard
        GrafanaDashBoardUrl: https://g.console.aliyun.com/d/549c2bf8936f7767ea6ac47c47b00f2a/mysql-exporter-quickstart-and-dashboard?orgId=355401&refresh=10s&var-datasource=cloud-product-prometheus_cn-hongkong_cn-mariadb_1563457855438522_135830&var-job=All&var-instance=All
  ServiceType: managed
  IsSupportOperated: true
  PolicyNames: AliyunComputeNestPolicyForFullAccess
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: Mysql ACK容器多租户yaml部署
    Image: 'icons/mysql_log.jpeg'
    Name: Mysql ACK容器yaml部署
  ShareType: Public
  ApprovalType: Manual